services:
  api:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ./:/app
    command: >
      sh -c "pip install -r requirements.txt
             && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ./:/app
    command: >
      sh -c "pip install -r requirements.txt
             && celery -A app.celery_app.celery_app worker --loglevel=INFO"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
